name: archery
version: 1.4.1
description: Archery is a high-performance, full-featured web framework for Dart.
repository: https://github.com/webarchery/archery
environment:
  sdk: ^3.10.9

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  uuid: ^4.5.1
  crypto: ^3.0.3
  http: ^1.5.0
  intl: ^0.20.0
  collection: ^1.19.1
  sqflite_common_ffi: ^2.3.6
  ffi: ^2.1.4
  mime: ^2.0.0
  postgres: ^3.5.9

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
